#!/bin/bash
mkdir logs
timestamp=$(date +%s)
password="safe-ahead"
track="keimola"
echo "Starting safe-ahead test run with 2 fast and 2 crash bots. Logs are available under logs/${timestamp}_bot_{1-4}.log"
echo "Results should be available in about 4 minutes"
echo "Starting bot 3"
./default_run --track=$track --num_players=4 --bot_algorithm=tomek --bot=NFC-0.75 --host=prost.helloworldopen.com --password=${password} --disable_visualizer=true --continuous_integration > logs/${timestamp}_bot_3.log &
sleep 2
echo "Starting bot 4"
./default_run --track=$track --num_players=4 --bot_algorithm=tomek --bot=NFC-0.65 --host=prost.helloworldopen.com --password=${password} --disable_visualizer=true --continuous_integration > logs/${timestamp}_bot_4.log &
sleep 2
echo "Starting bot 1"
./default_run --track=$track --num_players=4 --bot_algorithm=stepping --bot=NFC-Boss-1 --log_masks=false --disable_visualizer=true --host=prost.helloworldopen.com --password=${password} --continuous_integration --nolog_schedule --log_overtaking --switch_scheduler=NeverSwitchScheduler --disable_attack --log_position > logs/${timestamp}_bot_1.log &
sleep 2
echo "Starting bot 2"
./default_run --track=$track --num_players=4 --bot_algorithm=stepping --bot=NFC-Boss-2 --log_masks=false --disable_visualizer=true --host=prost.helloworldopen.com --password=${password} --continuous_integration --nolog_schedule --log_overtaking --switch_scheduler=NeverSwitchScheduler --disable_attack > logs/${timestamp}_bot_2.log &
echo "Running..."
