#!/bin/bash

mkdir -p bin

function build_with_cmake() {
  cd bin
  cmake ..
  make -j4
  make test
  cd ..
}

function build_without_cmake() {
  date
  # Build without cmake
  flags="-std=c++11 -I jsoncons/src/ -I . -l pthread -l boost_system -o bin/bot"
  g++ $flags \
    main.cpp \
    utils/protocol.cpp utils/connection.cpp utils/game_visualizer.cpp \
    bots/raw_bot.cpp bots/tomek/bot.cpp bots/piotr/bot.cpp bots/greedy/bot.cpp bots/basic/bot.cpp bots/stepping/bot.cpp \
    game/car.cpp game/car_tracker.cpp game/command.cpp game/gauss.cpp game/position.cpp game/race.cpp game/result.cpp game/simplex.cpp game/track.cpp game/turbo.cpp \
    gflags/gflags.cc gflags/gflags_reporting.cc gflags/gflags_completions.cc \
    physics/speed_tracker.cpp
}

if type cmake >/dev/null 2>&1 && [ "$1" != "skip_cmake" ]; then
  build_with_cmake
else
  build_without_cmake
fi
