#!/bin/bash

mkdir -p bin

function build_with_cmake() {
  cd bin
  cmake ..
  make -j4
  make test
  cd ..
}

function build_without_cmake() {
  date
  git rev-parse HEAD
  # Build without cmake
  flags="-O2 -std=c++11 -I jsoncons/src/ -I . -l pthread -l boost_system -l boost_filesystem -o bin/bot"
  g++ $flags \
    main.cpp common_flags.cpp \
    utils/protocol.cpp utils/connection.cpp utils/game_visualizer.cpp \
    bots/raw_bot.cpp bots/tomek/bot.cpp bots/piotr/bot.cpp bots/greedy/bot.cpp bots/basic/bot.cpp bots/stepping/bot.cpp bots/constant/bot.cpp bots/kamikaze/bot.cpp \
    game/car.cpp game/car_tracker.cpp game/command.cpp game/gauss.cpp game/position.cpp game/race.cpp game/result.cpp game/simplex.cpp game/track.cpp game/turbo.cpp game/lane_length_model.cpp game/radius_model.cpp game/approximation.cpp game/drift_model.cpp game/enemy_tracker.cpp game/race_tracker.cpp game/bump_tracker.cpp \
    schedulers/binary_throttle_scheduler.cpp schedulers/shortest_path_switch_scheduler.cpp schedulers/greedy_turbo_scheduler.cpp schedulers/bulk_scheduler.cpp schedulers/learning_scheduler.cpp \
    gflags/gflags.cc gflags/gflags_reporting.cc gflags/gflags_completions.cc \
    physics/speed_tracker.cpp
}

if type cmake >/dev/null 2>&1 && [ "$1" != "skip_cmake" ]; then
  build_with_cmake
else
  build_without_cmake
fi
